# GET all persons
GET http://localhost:3001/api/persons/

###

# POST a new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "apple",
  "number": "456745687"
}

###

# GET a person by ID
GET http://localhost:3001/api/persons/67c41b25ea9d8d390c3dba12

###

# PUT (update) a person by ID
PUT http://localhost:3001/api/persons/67c41b25ea9d8d390c3dba12
Content-Type: application/json

{
  "name": "Updated Name",
  "number": "123456789"
}

###

# DELETE a person by ID
DELETE http://localhost:3001/api/persons/67c41b25ea9d8d390c3dba12
