# GET all persons
GET http://localhost:3001/api/persons/

###

Get http://localhost:3001/api/persons/user/67c8e476f4a658af01b4b150


# POST a new person
### Add a person to the first user (root)
POST http://localhost:3001/api/persons/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YzhlNDc2ZjRhNjU4YWYwMWI0YjE1MCIsImlhdCI6MTc0MTIyMzk4OX0.yTpFRV0aM84hHTC8_MT6NcXG7SI-B9qgDY6h0-YZh9c

{
  "name": "TOKENCHECK",
  "number": "444444"
}

### Add first person to second user (john_doe)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Bob",
  "number": "987654321",
  "userId": "67c8e479f4a658af01b4b152"
}

### Add second person to second user (john_doe)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Charlie",
  "number": "555666777",
  "userId": "67c8e479f4a658af01b4b152"
}

### Add first person to third user (jane_doe)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "David",
  "number": "111222333",
  "userId": "67c8e47bf4a658af01b4b154"
}

### Add second person to third user (jane_doe)
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Eve",
  "number": "444555666",
  "userId": "67c8e47bf4a658af01b4b154"
}

###

# GET a person by ID
GET http://localhost:3001/api/persons/67c41b25ea9d8d390c3dba12

###

# PUT (update) a person by ID
PUT http://localhost:3001/api/persons/67c41b25ea9d8d390c3dba12
Content-Type: application/json

{
  "name": "Updated Name",
  "number": "123456789"
}

###

# DELETE a person by ID
DELETE http://localhost:3001/api/persons/67c57c98a3e98ac51f74a9e6
